# Generated by Django 3.2.2 on 2021-09-20 13:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('unical_accounts', '0002_auto_20180806_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name_plural': 'Utenti PEO'},
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=30, null=True, verbose_name='Luogo di nascita'),
        ),
    ]
