# Generated by Django 3.2.2 on 2021-07-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0034_auto_20191213_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulodomandabando',
            name='punteggio_manuale',
            field=models.FloatField(blank=True, help_text='punteggio attribuito dalla commissione', null=True),
        ),
    ]
