# Generated by Django 3.2.2 on 2022-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0036_alter_modulodomandabando_punteggio_manuale'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulodomandabando',
            name='tipo_caricamento_modulo',
            field=models.CharField(choices=[('automatico', 'Automatico'), ('manuale', 'Manuale'), ('automatico_mod', 'Automatico (modificato)')], default='manuale', max_length=20),
        ),
        migrations.AlterField(
            model_name='modulodomandabando',
            name='punteggio_calcolato',
            field=models.FloatField(blank=True, help_text='popolato dal metodo calcolo_punteggio', null=True),
        ),
    ]
