# Generated by Django 3.2.2 on 2022-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domande_peo', '0037_auto_20220502_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='domandabando',
            name='punteggio_prestazione_individuale',
            field=models.FloatField(blank=True, null=True, verbose_name='Punteggio prestazione individuale'),
        ),
        migrations.AddField(
            model_name='domandabando',
            name='punteggio_prestazione_individuale_manuale',
            field=models.FloatField(blank=True, help_text='impostato manualmente', null=True, verbose_name='Punteggio prestazione individuale MANUALE'),
        ),
        migrations.AlterField(
            model_name='domandabando',
            name='punteggio_calcolato',
            field=models.FloatField(blank=True, help_text="popolato da metodo calcolo_punteggio_domanda, comprensivo di quello derivante dall'anzianità", null=True),
        ),
    ]
