# Generated by Django 3.2.2 on 2021-07-16 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0032_merge_20191111_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livelloposizioneeconomica',
            name='nome',
            field=models.CharField(help_text='Tradizionalmente: 1, 2, 3, 4, 5, 6 ma o qualsivoglia valore', max_length=255, verbose_name='Livello Posizione Economica'),
        ),
        migrations.CreateModel(
            name='FormazioneDipendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('matricola', models.CharField(max_length=6)),
                ('partecipante', models.CharField(blank=True, default='', help_text='Valore letto in fase di importazione', max_length=254)),
                ('evento_formativo', models.CharField(help_text='Evento formativo', max_length=255)),
                ('ente_organizzatore', models.CharField(help_text='Ente organizzatore', max_length=255)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('durata_ore', models.FloatField(default=0.0)),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('is_active', models.BooleanField(default=True, verbose_name='Visibile agli utenti')),
                ('dipendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.dipendente')),
            ],
            options={
                'verbose_name': 'Formazione dipendente',
                'verbose_name_plural': 'Formazione dipendenti',
                'ordering': ('ordinamento',),
            },
        ),
    ]
