# Generated by Django 3.2.2 on 2021-07-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0033_auto_20210716_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazionedipendente',
            name='dipendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.dipendente'),
        ),
        migrations.AlterField(
            model_name='formazionedipendente',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Attivo'),
        ),
    ]
