# Generated by Django 3.2.2 on 2021-08-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0034_auto_20210716_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='dipendente',
            name='data_ultima_progressione',
            field=models.DateField(blank=True, null=True, verbose_name='Data ultima progressione calcolata (CSA)'),
        ),
    ]
