# Generated by Django 3.2.2 on 2021-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0035_dipendente_data_ultima_progressione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazionedipendente',
            name='durata_ore',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
