# Generated by Django 3.2.2 on 2021-09-20 13:35

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0036_alter_formazionedipendente_durata_ore'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunzioneNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('funzione', models.CharField(max_length=7)),
                ('descr', models.CharField(max_length=100)),
                ('id_code', models.CharField(help_text='Lettera, numero o sequenza', max_length=33, verbose_name='Codice identificativo')),
            ],
            options={
                'verbose_name': 'Nomina nella funzione',
                'verbose_name_plural': 'Nomina nelle funzioni',
            },
        ),
    ]
