# Generated by Django 3.2.2 on 2021-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0037_funzionenomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funzionenomina',
            name='id_code',
            field=models.CharField(blank=True, help_text='Lettera, numero o sequenza', max_length=33, null=True, verbose_name='Codice identificativo'),
        ),
    ]
