# Generated by Django 3.2.2 on 2022-05-10 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0038_alter_funzionenomina_id_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestazioneIndividuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('matricola', models.CharField(max_length=6)),
                ('partecipante', models.CharField(blank=True, default='', help_text='Valore letto in fase di importazione', max_length=254)),
                ('valutazione', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('punteggio_finale', models.PositiveIntegerField(blank=True, default=0, help_text='punteggio')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('dipendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.dipendente')),
            ],
            options={
                'verbose_name': 'Prestazione individuale',
                'verbose_name_plural': 'Prestazioni individuali',
            },
        ),
    ]
