# Generated by Django 3.2.2 on 2022-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0039_prestazioneindividuale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestazioneindividuale',
            name='id',
        ),
        migrations.AlterField(
            model_name='prestazioneindividuale',
            name='matricola',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
