# Generated by Django 3.2.2 on 2021-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0097_auto_20210117_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punteggio_titolostudio',
            name='punteggio',
            field=models.FloatField(),
        ),
    ]
