# Generated by Django 3.2.2 on 2021-06-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0098_auto_20210623_1427'),
    ]

    operations = [   
        migrations.CreateModel(
            name='SubModuloInserimentoCampi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('CustomSignedP7MField', 'Allegato P7M firmato'), ('CustomFileField', 'Allegato PDF'), ('CustomSignedPdfField', 'Allegato PDF firmato'), ('CustomHiddenField', 'Campo nascosto'), ('CheckBoxField', 'Checkbox'), ('BaseDateField', 'Data'), ('PEO_BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora'), ('PEO_BaseDateTimeField', 'Data e Ora'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('DurataComeInteroField', 'Durata come numero intero (anni,mesi,ore)'), ('CustomEmailField', 'E-mail'), ('CustomComplexTableField', 'Inserimenti multipli'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo'), ('PEO_AnnoInRangeOfCarrieraField', '_PEO_  Anno singolo IN RANGE of bando'), ('PEO_DateInRangeComplexField', '_PEO_  Data inizio e Data fine IN RANGE of bando'), ('PEO_DateInRangeInCorsoComplexField', "_PEO_  Data inizio e Data fine IN RANGE of bando + 'In corso'"), ('PEO_DateOutOfRangeComplexField', '_PEO_  Data inizio e Data fine OUT OF RANGE of bando'), ('PEO_DataLowerThanBandoField', '_PEO_  Data singola IN RANGE of bando'), ('PEO_ProtocolloField', '_PEO_  Protocollo (tipo/numero/data)'), ('PEO_PunteggioFloatField', '_PEO_  Punteggio (numero con virgola)'), ('PEO_SubDescrizioneIndicatoreField', '_PEO_  Selezione sotto-categorie DescrizioneIndicatore'), ('PEO_TitoloStudioField', '_PEO_  Titoli di studio'), ('PEO_DateStartEndComplexField', '_PEO_ Data inizio e Data fine')], max_length=100)),
                ('valore', models.CharField(blank=True, default='', help_text="Viene considerato solo se si sceglie 'Menu a tendina' oppure 'Serie di Opzioni'. (Es: valore1;valore2;valore3...)", max_length=255, verbose_name='Lista di Valori')),
                ('is_required', models.BooleanField(default=True)),
                ('aiuto', models.CharField(blank=True, default='', max_length=254)),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('descrizione_indicatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.subdescrizioneindicatore')),
            ],
            options={
                'verbose_name': 'Modulo di inserimento',
                'verbose_name_plural': 'Moduli di inserimento',
                'ordering': ('ordinamento',),
            },
        ),
    ]
