# Generated by Django 3.2.2 on 2021-09-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_risorse_umane', '0037_funzionenomina'),
        ('gestione_peo', '0099_auto_20210624_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punteggio_titolostudio',
            options={'ordering': ['ordinamento'], 'verbose_name': 'Punteggio per Titolo di Studio', 'verbose_name_plural': 'Punteggi per Titolo di Studio'},
        ),
        migrations.AlterField(
            model_name='bando',
            name='protocollo_cod_titolario',
            field=models.CharField(blank=True, choices=[('07/01', '07/01')], max_length=12, null=True, verbose_name='Codice titolario'),
        ),
        migrations.AlterField(
            model_name='moduloinserimentocampi',
            name='field_type',
            field=models.CharField(choices=[('CustomSignedP7MField', 'Allegato P7M firmato'), ('CustomFileField', 'Allegato PDF'), ('CustomSignedPdfField', 'Allegato PDF firmato'), ('CustomHiddenField', 'Campo nascosto'), ('CheckBoxField', 'Checkbox'), ('BaseDateField', 'Data'), ('PEO_BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora'), ('PEO_BaseDateTimeField', 'Data e Ora'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('DurataComePositiveFloatField', 'Durata come numero decimale (anni,mesi,ore)'), ('DurataComeInteroField', 'Durata come numero intero (anni,mesi,ore)'), ('CustomEmailField', 'E-mail'), ('CustomComplexTableField', 'Inserimenti multipli'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo'), ('PEO_URLField', 'URL'), ('PEO_AllegatoURLField', '_PEO_  Allegato o URL al documento'), ('PEO_AnnoInRangeOfCarrieraField', '_PEO_  Anno singolo IN RANGE of bando'), ('PEO_DateInRangeComplexField', '_PEO_  Data inizio e Data fine IN RANGE of bando'), ('PEO_DateInRangeInCorsoComplexField', "_PEO_  Data inizio e Data fine IN RANGE of bando + 'In corso'"), ('PEO_DateOutOfRangeComplexField', '_PEO_  Data inizio e Data fine OUT OF RANGE of bando'), ('PEO_DataLowerThanBandoField', '_PEO_  Data singola IN RANGE of bando'), ('PEO_ProtocolloField', '_PEO_  Protocollo (tipo/numero/data)'), ('PEO_PunteggioFloatField', '_PEO_  Punteggio (numero con virgola)'), ('PEO_SubDescrizioneIndicatoreField', '_PEO_  Selezione sotto-categorie DescrizioneIndicatore'), ('PEO_SubDescrizioneIndicatoreFormField', '_PEO_  Selezione sotto-categorie con form DescrizioneIndicatore'), ('PEO_TitoloStudioField', '_PEO_  Titoli di studio'), ('PEO_DateStartEndComplexField', '_PEO_ Data inizio e Data fine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='punteggio_descrizioneindicatore_timedelta',
            name='operatore',
            field=models.CharField(choices=[('x', 'moltiplicatore'), ('a', 'assegnazione'), ('+', 'addizione'), ('/', 'divisione'), ('-', 'sottrazione'), ('p', 'punteggio_ogni_3_ore_max_02'), ('q', 'punteggio_ogni_5_ore_max_06'), ('r', 'punteggio_ogni_5_ore_max_05'), ('s', 'punteggio_ogni_5_ore_max_04')], default='a', help_text="Operatore che determina l'assegnazione", max_length=1, verbose_name='Operatore da applicare al punteggio'),
        ),
        migrations.AlterField(
            model_name='punteggio_subdescrizioneindicatore_timedelta',
            name='operatore',
            field=models.CharField(choices=[('x', 'moltiplicatore'), ('a', 'assegnazione'), ('+', 'addizione'), ('/', 'divisione'), ('-', 'sottrazione'), ('p', 'punteggio_ogni_3_ore_max_02'), ('q', 'punteggio_ogni_5_ore_max_06'), ('r', 'punteggio_ogni_5_ore_max_05'), ('s', 'punteggio_ogni_5_ore_max_04')], default='a', help_text="Operatore che determina l'assegnazione", max_length=1, verbose_name='Operatore da applicare al punteggio'),
        ),
        migrations.AlterField(
            model_name='submoduloinserimentocampi',
            name='field_type',
            field=models.CharField(choices=[('CustomSignedP7MField', 'Allegato P7M firmato'), ('CustomFileField', 'Allegato PDF'), ('CustomSignedPdfField', 'Allegato PDF firmato'), ('CustomHiddenField', 'Campo nascosto'), ('CheckBoxField', 'Checkbox'), ('BaseDateField', 'Data'), ('PEO_BaseDateField', 'Data'), ('BaseDateTimeField', 'Data e Ora'), ('PEO_BaseDateTimeField', 'Data e Ora'), ('DateStartEndComplexField', 'Data inizio e Data fine'), ('DurataComePositiveFloatField', 'Durata come numero decimale (anni,mesi,ore)'), ('DurataComeInteroField', 'Durata come numero intero (anni,mesi,ore)'), ('CustomEmailField', 'E-mail'), ('CustomComplexTableField', 'Inserimenti multipli'), ('CustomRadioBoxField', 'Lista di opzioni (checkbox)'), ('CustomSelectBoxField', 'Lista di opzioni (tendina)'), ('PositiveFloatField', 'Numero con virgola positivo'), ('PositiveIntegerField', 'Numero intero positivo'), ('ProtocolloField', 'Protocollo (tipo/numero/data)'), ('CustomCharField', 'Testo'), ('TextAreaField', 'Testo lungo'), ('PEO_URLField', 'URL'), ('PEO_AllegatoURLField', '_PEO_  Allegato o URL al documento'), ('PEO_AnnoInRangeOfCarrieraField', '_PEO_  Anno singolo IN RANGE of bando'), ('PEO_DateInRangeComplexField', '_PEO_  Data inizio e Data fine IN RANGE of bando'), ('PEO_DateInRangeInCorsoComplexField', "_PEO_  Data inizio e Data fine IN RANGE of bando + 'In corso'"), ('PEO_DateOutOfRangeComplexField', '_PEO_  Data inizio e Data fine OUT OF RANGE of bando'), ('PEO_DataLowerThanBandoField', '_PEO_  Data singola IN RANGE of bando'), ('PEO_ProtocolloField', '_PEO_  Protocollo (tipo/numero/data)'), ('PEO_PunteggioFloatField', '_PEO_  Punteggio (numero con virgola)'), ('PEO_SubDescrizioneIndicatoreField', '_PEO_  Selezione sotto-categorie DescrizioneIndicatore'), ('PEO_SubDescrizioneIndicatoreFormField', '_PEO_  Selezione sotto-categorie con form DescrizioneIndicatore'), ('PEO_TitoloStudioField', '_PEO_  Titoli di studio'), ('PEO_DateStartEndComplexField', '_PEO_ Data inizio e Data fine')], max_length=100),
        ),
        migrations.CreateModel(
            name='FunzioneNomina_SubDescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('funzione_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.funzionenomina', verbose_name='Funzione')),
                ('sub_descrizione_indicatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.subdescrizioneindicatore', verbose_name='Sub Descrizione Indicatore')),
            ],
            options={
                'verbose_name': 'Funzione nomina per sub descrizione indicatore',
                'verbose_name_plural': 'Funzioni nomina per sub descrizione indicatore',
            },
        ),
        migrations.CreateModel(
            name='FunzioneNomina_DescrizioneIndicatore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinamento', models.PositiveIntegerField(blank=True, default=0, help_text="posizione nell'ordinamento")),
                ('descrizione_indicatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_peo.descrizioneindicatore', verbose_name='Descrizione Indicatore')),
                ('funzione_nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione_risorse_umane.funzionenomina', verbose_name='Funzione nomina')),
            ],
            options={
                'verbose_name': 'Funzione nomina per descrizione indicatore',
                'verbose_name_plural': 'Funzioni nomina per descrizione indicatore',
            },
        ),
    ]
