# Generated by Django 3.2.2 on 2022-05-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_peo', '0100_auto_20210920_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatoreponderato',
            name='add_punteggio_anzianita',
        ),
    ]
